app:
    appname: "bluebell"
    version: "v0.0.1"
    port: 8080

log:
    filename: "./test.log"
    level: "info"
    mode: "dev" # dev(console+file), prod(only file)

mysql:
    user: "root"
    password: "123456"
    host: "127.0.0.1"
    port: 3306
    dbname: "bluebell"

redis:
    host: "127.0.0.1"
    port: 6379
    password: ""
    poolsize: 20
    protocol: 2
    db: 0

snowflake:
    start_time: "2026-04-28"
    machine_id: 1
